### ISSUE TITLE
@TransactionalRestController, is that something really needed?

### ISSUE THREAD

**Issue by mdeinum** [sbrannen/spring-composed#11]
Just trying to spark some discussion about the `@TransactionalRestController`

I always considered putting `@Transactional` on your web layer is a bad practice as the layer below that should drive your transaction (especially if you have different ways of exposing your services, SOAP, REST, ...). 

So I would argue that this annotation is promoting an anti-pattern. Of course I can refrain from using it but adding this to the framework might lead to people thinking that this is a good idea (or pattern) to use.

**Comment by jhoeller** [comment]
I would go even further and question whether we need `@Transactional**Component` in the first place. `@Transactional @Controller` is barely longer than `@TransactionalController`, so where's the convenience? I just see plenty of permutations here and no real gain.

**Comment by rstoyanchev** [comment]
Plus you're looking at using cglib or putting @RequestMapping on an interface. Hardly convenient.

**Comment by sbrannen** [comment]
Hi guys,

I agree that `@TransactionalRestController` is likely not the best idea and more likely an anti-pattern.

With that in mind, I do not believe we would ever include this as an official annotation in Spring, but my goal thus far is to allow the community to brainstorm about the possibilities with _composed annotations_ and `@AliasFor`. So we'll leave `@TransactionalRestController` as it is for now and let the discussions continue. :wink:

**Comment by sbrannen** [comment]
@jhoeller, are you arguing against `@TransactionalService` and `@TransactionalRepository` as well, or just against `@Transactional*Controller`?

**Comment by sbrannen** [comment]
Closing this issue since we are all in agreement that `@TransactionalRestController` is not a good idea for inclusion in the Spring Framework.
