### ISSUE TITLE
allow composition of anotation member values

### ISSUE THREAD

**Issue by cforce** [sbrannen/spring-composed#14]
e.g create an anotation A which inherits from RequestMapping.
Anotation A has member String apiVersion() and apiDomain().
Anotation A then overwrites (via aliasing) "path" with (default) value = apiDomain()+"/"+apiVersion()+"/"+path().
I am not sure if this is even possible by using aliasing.

**Comment by sbrannen** [comment]
No, such functionality is not possible via aliasing since annotation attributes must be constant values.

Such a feature would require specific code within the core annotation processing algorithms in Spring and is beyond the scope of _Spring Composed_.

I am therefore closing this issue.

**Comment by rstoyanchev** [comment]
You can embed property placeholders resolved from an external property source. For example at the class level `@RequestMapping(path="${myPrefix}")` (re-used across all methods including sub-classes). and then at the method level `@RequestMapping(path="/myPath")`. 

See also similar discussion here https://jira.spring.io/browse/SPR-13882.

**Comment by cforce** [comment]
If I want Feign to make use of th server side mvc interface path anotation this won't work as I would then copy paste the configuration in external propertysource from server to client artifact. My approach now is to have an architectural constraint for service/apityp/domain/ URL beeing enforced by introspection on startup. It's activated by an boot starter as part of my microservice framework
