### ISSUE TITLE
@PostJson needs produces too - e.g. search form

### ISSUE THREAD

**Issue by nealeu** [sbrannen/spring-composed#18]
I'm giving this a go and it's a great feature for Spring that simplifies life no end.

What's missing though is that `@PostJson` needs the `produces` parameter, as this is still valid for a POST with something like a search form.

**Comment by sbrannen** [comment]
Hi @nealeu,

Glad you like it!

Please note, however, that content-specific annotations like `@PostJson` will not be included in core Spring. The ones that got into Spring Framework 4.3 include `@GetMapping`, `@PutMapping`, `@PostMapping`, `PatchMapping`, and `@DeleteMapping`.

**Comment by sbrannen** [comment]
In any case, I added the `produces` attribute to the remaining `@Post*` annotations in 0acc3939647545653b9f2d3543acfce0b809e3d3.

**Comment by nealeu** [comment]
Cool.  Thanks.  Sounds like it'll make sense to have a version of spring-composed end up in Maven central at some point, given only a fraction made Spring 4.3

**Comment by sbrannen** [comment]
Hi @nealeu,

As stated in the README, _the current goal of this project is to brainstorm within the community and gather ideas on what kinds of composed annotations would be useful for Spring to officially support._

So with that in mind, _Spring Composed_ is really just a playground for experimentation, and we intend to keep it as such. In other words, we don't have any plans to ever officially _release_ these annotations in Maven central (other than those directly incorporated into official Spring projects).

Bear in mind, however, that it's dead simple to reproduce such annotations in your own projects.
