### ISSUE TITLE
Twice Path

### ISSUE THREAD

**Issue by bingyupj** [sbrannen/spring-composed#20]
although path is an alias for value,Twice Path  is Ok ?

```java
@AliasFor(annotation = RequestMapping.class, attribute = "path")
String[] value() default {};

@AliasFor(annotation = RequestMapping.class, attribute = "path")
String[] path() default {};
```

**Comment by sbrannen** [comment]
Yes. This is well documented in the [Javadoc for @AliasFor](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/core/annotation/AliasFor.html).
