### ISSUE TITLE
Publish spring-composed JAR in a repository

### ISSUE THREAD

**Issue by sdeleuze** [sbrannen/spring-composed#5]
Could spring-composed snapshots be available from a Maven repository?

**Comment by sbrannen** [comment]
That would certainly be nice!

Any thoughts on how to accomplish that in the easiest way?

**Comment by sdeleuze** [comment]
I think the more suitable repositories are https://repo.spring.io/libs-snapshot or https://bintray.com. Maybe the choice is linked to another question, do you plan to keep this project here or move it to https://github.com/spring-projects ;-)

In terms of CI, if repo.spring.io is chosen, we should create a build on build.spring.io (I can do that if you want). If Bintray is chosen, using Travis CI is an option (there is something about that in one of the pending pull requests).

We also need to define in Gradle configuration the `group`  to something like `org.springframework.composed`, and define `version` (the `jar.version` already defined is not taken in account, maybe we should define it in a `gradle.properties` file with Spring convention `X.Y.Z.BUILD-SNAPSHOT`). When I saw that I was planning to update my PR but you were to fast for me ;-)

**Comment by sdeleuze** [comment]
FYI the additional changes I made in my fork, let me know if you want a PR for that:
https://github.com/sdeleuze/spring-composed/commit/124521db71a560894c7bd220d93a977da2445293

**Comment by sbrannen** [comment]
yes, PR, please!

**Comment by sbrannen** [comment]
I think we should move this to spring-projects.

If you could go ahead and set up a build on build.spring.io, that would be great!

**Comment by sdeleuze** [comment]
Done: https://github.com/sbrannen/spring-composed/pull/6

Sure, I will do that shortly.

**Comment by sdeleuze** [comment]
I have created the [build job](https://build.spring.io/browse/SC-PUB), and it deploys the spring-composed JAR on repo.spring.io:
- http://repo.spring.io/snapshot/org/springframework/composed/spring-composed/1.0.0.BUILD-SNAPSHOT/spring-composed-1.0.0.BUILD-SNAPSHOT.jar
- http://repo.spring.io/snapshot/org/springframework/composed/spring-composed/1.0.0.BUILD-SNAPSHOT/spring-composed-1.0.0.BUILD-SNAPSHOT.pom

2 remarks:
- Not sure the 1.8 minimum requirement (`targetCompatibility = 1.8`) is mandatory, I would expect the same requirement than Spring Framework
- Feel free to reuse https://github.com/spring-projects/spring-reactive/commit/0a4277a785c7aafa0856ac503724048d765c3f13 to update the README.md page

**Comment by sbrannen** [comment]
Awesome!

I've updated the [README](https://github.com/sbrannen/spring-composed/blob/master/README.md) accordingly.

Merci beaucoup! :smile:
